{% set version = "1.0.15" %}

package:
  name: theano-pymc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/T/Theano-PyMC/Theano-PyMC-{{ version }}.tar.gz
  sha256: ba105ddf8d83bbbe159e9ad1d5128c400c6cffeda662eb77203f786ee816db09
  patches:

build:
  number: 0
  entry_points:
    - theano-cache = bin.theano_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - pygpu >=0.7.0,<0.8
    - jax  # [py>=37 and not win]

test:
  imports:
    - theano
  commands:
    - theano-cache help

about:
  home: http://deeplearning.net/software/theano/
  license: BSD-3-Clause
  summary: Fork of Theano for PyMC3. An optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/Theano-PyMC/
  doc_url: http://deeplearning.net/software/theano/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
